### ISSUE TITLE
Doc: Use ASCIDOC to deploy documentation

### ISSUE THREAD

**Issue by jdsika** [Lichtblick-Suite/asam-osi-utilities#3]
We need help from @philipwindecker to integrate the API Doxygen docu and an opinion. Maybe deploy first in this repo and then later integrate?

**Comment by philipwindecker** [comment]
I'll check with the office regarding budget and get back to you next week.

**Comment by pmai** [comment]
I don't think this should be integrated into the OSI documentation. This is a stand-alone open source software module and not part of the standard, hence no need to confuse people. There will just be a pointer to this package in non-normative text of the standard, and that's it.

Any further integration would make this part of the standard release process, and we do not want that, among other things.

**Comment by pmai** [comment]
@philipwindecker see my comment above; I think if anything then this needs its own documentation work, and we'll have to see how to fund that if needed, but right now I would keep this at arms length from the standard (similar to checker bundles vs. standards).

**Comment by philipwindecker** [comment]
Ok, let me know when/if you'd like my support on this in the future, then. :)

**Comment by jdsika** [comment]
I propose to deploy the docu here through a workflow in this local repository. We add the link then here:
![grafik](https://github.com/user-attachments/assets/cfabd1bd-4424-4e7d-9b38-e5f10b787531)

**Comment by ClemensLinnhoff** [comment]
Not part of OSI anymore, so no doc deployment necessary.
